---
engines:
  duplication:
    enabled: false
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CleanCode/BooleanArgumentFlag:
        enabled: false
      Design/NpathComplexity:
        enabled: false
      Design/WeightedMethodCount:
        enabled: false
      CyclomaticComplexity:
        enabled: false
      exclude_fingerprints:
        - 784c39986d25550b82c5c4a4c2ae9def
        - 19e8758306fba7a8cd0d647a7667030e
        - 8b2ad9b25d63813d10e02a67d2f826ee
        - 0756ba9ddcc34b77785fdc58557a1856
        - ead9ccdda5c5ec749ddf293073c74028
        
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- tests/
- Documentation/
