#!/usr/bin/env php
<?php
/**************************************************************************
Copyright 2017 Benato Denis

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*****************************************************************************/

define('CLI_TOOLKIT', true);

global $argv;
global $argc;

//include the base application and perform basic operations
if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    die("You have to run 'php composer.phar install' to complete the installation!");
}

use Gishiki\Gishiki;

//initialize the framework
Gishiki::Initialize();

if ($argc > 1) {
    switch ($argv[1]) {
        case 'setup':
            Setup();
            break;
            
        case 'help':
            printf("The following is a list of arguments that can be passed to the gishiki CLI\n\n");
            printf("setup: generate an empty application\n");
            break;
            
        default:
            printf("invalid command: use gishiki help for a list of available commands\n");
            break;
    }
} else {
    printf("use gishiki help for a list of available commands\n");
}